exports.logs = {
  CREATE_USER: "CREATE_USER", // OK
  CONFIRM_EMAIL: "CONFIRM_EMAIL",
  EDIT_PASSWORD: "EDIT_PASSWORD",
  CHANGE_PLAIN: "CHANGE_PLAIN",
  SIGN_IN: "SIGN_IN", // OK
  SIGN_OUT: "SIGN_OUT", // OK

  CREATE_CARD: "CREATE_CARD", // OK
  EDIT_CARD: "EDIT_CARD", // OK
  CHANGE_CARD_STATUS: "CHANGE_CARD_STATUS",
  DELETE_CARD: "DELETE_CARD",

  CREATE_CATEGORY: "CREATE_CATEGORY", // OK
  EDIT_CATEGORY: "EDIT_CATEGORY", // OK
  DELETE_CATEGORY: "DELETE_CATEGORY",

  CREATE_SUBCATEGORY: "CREATE_SUBCATEGORY", // OK
  EDIT_SUBCATEGORY: "EDIT_SUBCATEGORY", // OK
  DELETE_SUBCATEGORY: "DELETE_SUBCATEGORY",

  CREATE_ASSET: "CREATE_ASSET", // OK
  EDIT_ASSET: "EDIT_ASSET", // OK
  DELETE_ASSET: "DELETE_ASSET",

  CREATE_EXPENSE: "CREATE_EXPENSE", // OK
  EDIT_EXPENSE: "EDIT_EXPENSE",
  DELETE_EXPENSE: "DELETE_EXPENSE",
  REPEAT_EXPENSE: "REPEAT_EXPENSE",

  CREATE_INCOME: "CREATE_INCOME", // OK
  EDIT_INCOME: "EDIT_INCOME",
  DELETE_INCOME: "DELETE_INCOME",
  REPEAT_INCOME: "REPEAT_INCOME",

  CREATE_INVESTIMENT: "CREATE_INVESTIMENT", // OK
  EDIT_INVESTIMENT: "EDIT_INVESTIMENT",
  DELETE_INVESTIMENT: "DELETE_INVESTIMENT",
  REPEAT_INVESTIMENT: "REPEAT_INVESTIMENT",

  CREATE_REDEMPTION: "CREATE_REDEMPTION", // OK
  EDIT_REDEMPTION: "EDIT_REDEMPTION",
  DELETE_REDEMPTION: "DELETE_REDEMPTION",
  REPEAT_REDEMPTION: "REPEAT_REDEMPTION",

  CREATE_DIVIDEND: "CREATE_DIVIDEND", // OK
  EDIT_DIVIDEND: "EDIT_DIVIDEND",
  DELETE_DIVIDEND: "DELETE_DIVIDEND",
  REPEAT_DIVIDEND: "REPEAT_DIVIDEND",

  CREATE_PORTFOLIO: "CREATE_PORTFOLIO", // OK
  EDIT_PORTFOLIO: "EDIT_PORTFOLIO",
  DELETE_PORTFOLIO: "DELETE_PORTFOLIO",

  CREATE_SUMMARY: "CREATE_SUMMARY", // OK
  EDIT_SUMMARY: "EDIT_SUMMARY", // OK
  DELETE_SUMMARY: "DELETE_SUMMARY",

  CREATE_SETTING: "CREATE_SETTING",
  EDIT_SETTING: "EDIT_SETTING",

  CREATE_BUDGET: "CREATE_BUDGET",
  EDIT_BUDGET: "EDIT_BUDGET",
  DELETE_BUDGET: "DELETE_BUDGET",
};
