const filterTypes = {
  START_DATE: 'START_DATE',
  END_DATE: 'END_DATE',
  TRANSACTION_TYPE: 'TRANSACTION_TYPE',
  CATEGORY: 'CATEGORY',
  SUBCATEGORY: 'SUBCATEGORY',
  GROUP_BY: 'GROUP_BY',
};

export default filterTypes;
