const steps = {
  DATE: 'DATE',
  TYPE: 'TYPE',
  CATEGORY: 'CATEGORY',
  SUBCATEGORY: 'SUBCATEGORY',
  VALUE: 'VALUE',
  PAYMENT: 'PAYMENT',
  CARD: 'CARD',
  INSTALLMENTS: 'INSTALLMENTS',
  OBSERVATION: 'OBSERVATION',
  CONFIRM: 'CONFIRM',
};

export default steps;
